# Generated by Django 3.2 on 2021-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
