name: 'backend'

# need on every push to enable heroku deploy even if no changes to backend were made
on:
  push:

jobs:
  django_test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test

  heroku_push:
    needs: django_test
    runs-on: ubuntu-latest
    if: contains('
      refs/heads/DEV
      refs/heads/master
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "project-les-frais"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
