name: 'frontend'

on:
  push:
    paths-ignore:
      - 'backend/**'
      - 'readme/**'
  pull_request:
    paths-ignore:
      - 'backend/**'
      - 'readme/**'

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    name: Node build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Install Node
        uses: actions/setup-node@master
        with:
          node-version: '12'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Perform Unit testing
        run: npm run test:unit

      - name: Perform End-to-End testing
        run: npm run test:e2e
