name: 'Heroku deploy'

on:
  workflow_run:
    workflows: [ "frontend", "backend" ]
    branches:
      - DEV
    types: [ completed ]

jobs:
  heroku_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1 # https://github.com/ahmadnassri/action-workflow-run-wait
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "project-les-frais"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
