name: 'Heroku deploy'

on:
  push:
    branches:
      - main
      - master
      - DEV

jobs:
  heroku_push:
    needs: [unit_testing, e2e_testing, django_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "project-les-frais"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
